# fly.toml app configuration file generated for radiolab-vue

app = "radiolab-vue"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile_pr"

[env]
  PORT = "8080"
  TZ = "America/New_York"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "30s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
